### ISSUE TITLE
Entidad Agenda Semanal

### ISSUE THREAD

**Issue by FedeBirge** [FedeBirge/HealthCooperationWeb#42]
Atención con el manejo de Map y JPA!  se consulta al LT por cualquier duda

**Comment by NataliaBrendaAndino** [comment]
No logre hacer el mapa con <Dias, List<Turno> >, pero funcionó y persistió como <Dias, Turno>

**Comment by NataliaBrendaAndino** [comment]
No logre hacer el mapa con una lista de turnos como valor de la llave Dias, pero funcionó y persistió como <Dias, Turno>
